name: update random.json
on: push
# on:
#   schedule:
#     - cron:  '*/5 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    # - name: Display Python version
    #   # run: python -c "import sys; print(sys.version)"
    #   run: ./scripts/update.py"

    - name: Display Python version
      # run: python -c "import sys; print(sys.version)"
      run: ./update.py
      # run: python ".\$GITHUB_WORKSPACE\scripts\update.py"

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
      #     external_repository: charlesjlee/bitcoin-beacon
      #     publish_dir: ./public
      #     user_name: Charles Lee
      #     user_email: charleslee592@gmail.com
      #     publish_branch: gh-pages