name: update random.json
on: push
# on:
#   schedule:
#     - cron:  '*/5 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: pip install datetime requests
        
    - name: Compute and over-write random.json
      run: python ./scripts/update.py

    - name: Commit changes
    - uses: actions/checkout@v2
    - run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Committing updated random.json"
        git push
